# Generated by Django 4.1.2 on 2022-10-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_a_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='jgljgl', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
